# Generated by Django 6.0.3 on 2026-04-21 00:10

import cuentas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nro_usuario',
            field=models.IntegerField(default=cuentas.models.get_user_number, unique=True),
        ),
    ]
