# Generated by Django 6.0.3 on 2026-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_producto_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cod_producto',
            field=models.IntegerField(unique=True),
        ),
    ]
