# Generated by Django 6.0.3 on 2026-03-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.DateField(blank='', default=None, null=True)),
                ('nro_cliente', models.IntegerField(unique=True)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
