# Generated by Django 6.0.3 on 2026-03-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Proveedores',
        ),
    ]
